### ISSUE TITLE
async error in jupyter notebook

### ISSUE THREAD

**Issue by masonproffitt** [iris-hep/func_adl#24]
I get an error from the following while running in a Jupyter notebook, which I *don't* get if I run from the basic Python interpreter:

```python
import func_adl
import func_adl_uproot
result = func_adl.EventDataset('file:///media/hd1/uproot-tutorial-file.root') \
         .Select("lambda e: e.nMuon") \
         .value(func_adl_uproot.ast_executor.evaluate)
```
```python
---------------------------------------------------------------------------
ObjectStreamException                     Traceback (most recent call last)
<ipython-input-4-6a988082a6f0> in <module>
----> 1 result = EventDataset('file:///media/hd1/uproot-tutorial-file.root') \
      2          .Select("lambda e: e.nMuon") \
      3          .value(uproot_ast_executor)

~/iris/code/func_adl/func_adl/ObjectStream.py in value(self, executor)
    176             pass
    177         if fail:
--> 178             raise ObjectStreamException('A python async event loop is already running. You must use future_value.')
    179 
    180         # Run our own event loop to make sure we get back the result and we are self contained

ObjectStreamException: A python async event loop is already running. You must use future_value.
```

The resulting behavior shouldn't depend on whether I'm running in a Jupyter notebook or not, so this is definitely a problem, but I'm not familiar enough yet with `asyncio` to immediately know how to fix this.

**Comment by gordonwatts** [comment]
Yeah... that is annoying. I don't know how to get around it. You have to use the async and await operators. The problem is I don't know how to detect if the async loop is running or not (so it will run in a notebook and also from the command line). 

I also go back and forth. Since as soon as you want to do something advanced (like 10 datasets at once) you will need the async operator. So perhpas that should be learned from the start?

OTOH, it should be simple. So if I could figure out how to detect this, I would.

Leaving open as it needs to be addressed.
